### ISSUE TITLE
Build booking GET endpoint

### ISSUE THREAD

**Issue by danieldietzler** [InformatikLK-LLG/mke#3]
- [x] Create the schema for the 'booking' database with [Spring Data JPA](https://spring.io/guides/gs/accessing-data-jpa/)
- [x] Create new bookingController & bookingRepository class
- [x] Build REST GET endpoint at '/booking' with [Spring REST](https://spring.io/guides/tutorials/rest/)
- [ ] Filter by optional parameters (multiple parameters might apply simultaneously)

**Comment by UZMSora** [comment]
Es ist Buchung, meine Kerle.

**Comment by rtschv** [comment]
it's booking, my kirles
