### ISSUE TITLE
Build customer GET endpoint

### ISSUE THREAD

**Issue by danieldietzler** [InformatikLK-LLG/mke#4]
- [x] Create the schema for the 'customer' database with [Spring Data JPA](https://spring.io/guides/gs/accessing-data-jpa/)
- [x] Create new customerController & customerRepository class
- [x] Build REST GET endpoint at '/customer' with [Spring REST](https://spring.io/guides/tutorials/rest/)
- [ ] Filter by optional parameters (multiple parameters might apply simultaneously)

**Comment by JNKPFR** [comment]
KundenNr., Vorname, Nachname, e-Mail, Telefonmobil, Telefondienstlich
